name: Build and Push Container Images

on:
  # workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-push-images:
    name: Build and Push Images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # Set up QEMU for cross-platform builds

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Set up Docker Buildx for building multi-architecture images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Login to Docker Hub with credentials stored in secrets

      - name: Build and Push for arm64
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            adrianpollub/zadanie2:ghlab10base-arm64
          platforms: linux/arm64/v8
          # Build and push container image for arm64 architecture

      - name: Build and Push for amd64
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            adrianpollub/zadanie2:ghlab10base-amd64
          platforms: linux/amd64
          # Build and push container image for amd64 architecture
